### ISSUE TITLE
Everything displays error when searching

### ISSUE THREAD

**Issue by sguergachi** [masterperas/es-everything-plugin#2]
When I search for anything I see the app pop up and this error box:
![image](https://cloud.githubusercontent.com/assets/615386/25918239/bd0c9404-3598-11e7-93ac-332c01d75fbb.png)

Seems it's appending the Cerebro path to the search string 'lab1'

**Comment by masterperas** [comment]
What is the path you set up in the settings?

also of note, you need to install the cli tool from Everything(https://www.voidtools.com/support/everything/command_line_interface/), that is es.exe file that the plugin is looking for.

From what i can gather you renamed your Everything.exe file to es.exe. That's why its failing.

**Comment by sguergachi** [comment]
Makes sense, thanks!

**Comment by HACKCHAMP** [comment]
![image](https://user-images.githubusercontent.com/14873743/29770925-e38866cc-8c0e-11e7-86cc-8c910acec589.png)

whenever I am trying to search the files i am getting this error.
I have set the path to "C:\Program Files\Everything\" where both everything and es.exe are present.

Can you help please.
