### ISSUE TITLE
Es.exe path

### ISSUE THREAD

**Issue by DBremen** [masterperas/es-everything-plugin#5]
Sorry, I'm new to Cerebro where do I need to configure the path the es.exe?

**Comment by lucasrlelis** [comment]
What worked for my is typing "Settings" in Cerebro. In the results, you should see "Search Everything Settings". In there, you can copy the path to the Everything folder.

**Comment by DBremen** [comment]
Hi @lucasrlelis,

thanks a lot. For some reason, I was not able to see the input field, but it's all good now. The path can also be set via "esevpluginpath": "PATHTOESEXEFOLDER\\" in config.json.

**Comment by Warmuser** [comment]
I'm sorry to reopen it, but I can't find a way to install properly the plugin. I have the same issue, so I tried to place the folder manually to these location and restart cerebro: C:\Users\User\AppData\Roaming\Cerebro\plugins\node_modules and also I tried to search the settings once I restarted the Cerebro app. Nothing happens. Please, write a guide for W10 users. Because, almost nobody understand how to properly install the plugins. 

Anyway, maybe should I add some value to the "package.json" file? 

{
  "name": "cerebro-plugins",
  "dependencies": {
    "cerebro-converter": "1.0.9",
    "cerebro-math": "1.0.0",
    "cerebro-google": "1.0.1",
    "cerebro-open-web": "1.0.0",
    "cerebro-basic-apps": "1.0.11",
    "cerebro-files-nav": "1.0.4"
  }
}

Please, help. Thanks!

**Comment by DBremen** [comment]
HI @Warmuser,

this is what worked for me:

1. Download es.exe from https://voidtools.com/downloads/
2. Unzip it into any folder you like e..g. "C:\Program Files (x86)\es"
3. Update the cerebro config file (%APPDATA%\Cerebro\config.json) with the path to the folder where you put es.exe
4. E.g. `"esevpluginpath": "C:\\Program Files (x86)\\es\\"` (the backlashes need to be escaped with another backslash)

**Comment by Warmuser** [comment]
Doesn't work for me.. I tried these: "esevpluginpath": C:\Program** Files (x86)\es\es-everything-plugin-master". Sigh..
